spring:
  application:
    name: AiProject
  # LANGCHAIN
  lang-chain:
    open-ai:
      # OPEN-AI API-KEY
      api-key: ${API_KEY}
      # OPEN-AI MODEL-NAME
      model-name: ${MODEL_NAME}
  datasource:
    # DB URL
    url: ${DB_URL}
    # DB USERNAME
    username: ${DB_USERNAME}
    # DB PASSWORD
    password: ${DB_PASSWORD}
  tessdata: ${TESSDATA_PREFIX}