spring:
  application:
    name: AiProject
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  # LANGCHAIN
  lang-chain:
    open-ai:
      # OPEN-AI API-KEY
      api-key: ${API_KEY}
      # OPEN-AI MODEL-NAME
      model-name: ${MODEL_NAME}
  datasource:
    # DB URL
    url: ${DB_URL}
    # DB USERNAME
    username: ${DB_USERNAME}
    # DB PASSWORD
    password: ${DB_PASSWORD}
  tessdata: ${TESSDATA_PREFIX}

logging:
  level:
    root: info
    web: info
    ai:
      agreement:
        AiProject: info
cors:
  allowed-origin:
    dev: ${CORS_DEV}
    prod: ${CORS_PROD}
security:
  api-key: ${SECURITY_API_KEY}